### ISSUE TITLE
Back-end solver parameters

### ISSUE THREAD

**Issue by ptal** [Dekker1/minizinc-slurm#42]
Hi,

Is it currently possible to pass additional parameters to the solver benchmarked?

In the IDE that was solved in [issue 113](https://github.com/minizinc/minizincide/issues/113).
I tried using `other_flags` but it doesn't seem to be working, see the error below using `Configuration(name="or-tools", solver=minizinc.Solver.lookup("com.google.or-tools"), other_flags={"--cp_disable_solve": ""})]`.

Thanks!

```
Traceback (most recent call last):
  File "/home/ptalbot/repositories/lattice-land/turbo/benchmarks/benchmarking/bench-bug.py", line 8, in <module>
    schedule(
  File "/home/ptalbot/repositories/mzn-bench/src/mzn_bench/mzn_slurm.py", line 148, in schedule
    main(Path(instances), Path(output_dir))
  File "/home/ptalbot/repositories/mzn-bench/src/mzn_bench/mzn_slurm.py", line 302, in main
    asyncio.run(
  File "/usr/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/ptalbot/repositories/mzn-bench/src/mzn_bench/mzn_slurm.py", line 201, in run_instance
    async for result in instance.solutions(
  File "/home/ptalbot/repositories/lattice-land/turbo/benchmarks/pybench/lib/python3.11/site-packages/minizinc/instance.py", line 393, in solutions
    async for obj in decode_async_json_stream(
  File "/home/ptalbot/repositories/lattice-land/turbo/benchmarks/pybench/lib/python3.11/site-packages/minizinc/json.py", line 99, in decode_async_json_stream
    obj = loads(buffer, cls=cls, **kw)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/__init__.py", line 359, in loads
    return cls(**kw).decode(s)
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by Dekker1** [comment]
The `other_flags` argument will accept any flags that are accepted on command line. It seems, however, that `--cp_disable_solve` is not an accepted command line flag:

```bash
~ 
❯ minizinc --solver or-tools --cp_disable_solve empty.mzn
minizinc: Unrecognized option or bad format `--cp_disable_solve'
minizinc: MiniZinc driver.
Usage: minizinc  [<options>] [-I <include path>] <model>.mzn [<data>.dzn ...] or just <flat>.fzn
More info with "minizinc --help"
```

It is likely missing from the `or-tools.msc` solver configutation file. It should be provided there in `extraFlags`.

**Comment by ptal** [comment]
I see! It works now. Thanks for the information.
